print("Enter a digit Alphabet capital or small")
a=(input())
print("If it is a digit")
print(a.isdigit())
print("If it is a alphabet")
print(a.isalpha())
print("If it is a small alphabet")
print(a.islower())
print("If it is a capital alphabet")
print(a.isupper())